In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3]) #1D

In [3]:
a2=np.array([[1,2,3],[4,5,6]]) #2D

In [12]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]) #3D

In [5]:
a1


array([1, 2, 3])

In [8]:
a1.shape

(3,)

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a2.shape


(2, 3)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
a3.shape #(depth,row,coloumn)

(3, 2, 3)

In [19]:
a3[0,0,0]

1

In [18]:
a3[2,0,2]

15

In [20]:
a3[1,0,2]

9

In [21]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [22]:
a2.dtype

dtype('int64')

In [23]:
b2=np.array([[1,2.4,3],[4,5.3,6]]) #2D

In [24]:
b2

array([[1. , 2.4, 3. ],
       [4. , 5.3, 6. ]])

In [25]:
b2.dtype

dtype('float64')

In [29]:
type(a1)

numpy.ndarray

In [28]:
test=[2, 1, 1]

In [31]:
type(test)

list

In [55]:
np_array=np.random.randint(10,size=(5,3))
np_array # change the values every time

array([[1, 5, 2],
       [4, 6, 3],
       [6, 4, 2],
       [8, 5, 8],
       [8, 7, 2]])

In [58]:
np.random.seed(0) # not change at each refresh
np_array0=np.random.randint(10,size=(5,3))
np_array0 

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [59]:
np.random.seed(1) # not change at each refresh
np_array1=np.random.randint(10,size=(5,3))
np_array1 

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [54]:
np_array.ndim

2

In [41]:
import pandas as pd
df=pd.DataFrame(np_array,columns=['x','y','z'])

In [42]:
df


x  y  z
0  5  4  2
1  7  3  7
2  4  1  2
3  5  9  8
4  5  4  4

In [46]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
c=np.ones(((3,2,5)))

In [51]:
c.dtype

dtype('float64')

In [48]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
np_array0 [0:2,1]

array([0, 7])

In [64]:
np_array0 [0,:]

array([5, 0, 3])